### PR TITLE
[#116] Fix missing .build() reference

### PR DESCRIPTION
**Pull request by er1c**
Oops, found a bug, ~~I'll drop this in for now and see about looking at the unit test again.~~

Added a unit test for this.

### CODE REVIEW

**Comment by er1c** [comment]
@aravindanranganathan-okta sorry looks like I missed something

**Comment by er1c** [comment]
@aravindanranganathan-okta friendly ping :)

**Comment by arvindkrishnakumar-okta** [comment]
Thanks for the PR @er1c 👍🏽 

Sorry for the delay, I'm currently out on vacation.

**Review by arvindkrishnakumar-okta — APPROVED** [review]

**Comment by er1c** [comment]
@arvindkrishnakumar-okta well, especially thank you then, I hope you are having an enjoyable holiday!

**Comment by arvindkrishnakumar-okta** [comment]
@er1c just released `0.5.3` 🎉

**Pull request merged**
